### ISSUE TITLE
Create A Darkmode

### ISSUE THREAD

**Issue by Sylk** [Sylk/wg-basic-layout#1]
Add a button to the top left, and allow that button to save users preference of dark mode vs. light mode.

On click of said button, allow the colors to change into a dark mode.

**Comment by ZaneKirk** [comment]
I've created the dark mode but don't have permissions to push it to your repo. I have just forked the project with this code included. Can be found [here](https://github.com/ZaneKirk/wg-basic-layout).

**Comment by Sylk** [comment]
You'll need to make a pull request from your repo to mine.
